config/routes.rb
RailStrap::Application.routes.draw do



  devise_for :users, :controllers => { :registrations => :registrations }
  devise_for :admins

  get '/token' => 'home#token', as: :token

  get '/admins/manage' => 'admins#manage', as: :manage

  get '/dashboard' => 'dashboard#index', as: :dashboard

  get '/u/:username' =>  'users#show', as: :user_profile
 
  resources :home, only: :index
  resources :admins

  root to: "dashboard#index"



end

app/models/admin.rb
class Admin < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://placehold.it/450"

  before_create :set_username
  # Remove dots and spaces from username
  before_save :format_username

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :lockable

  private
    def set_username
      self.username = self.email[/^[^@]+/].gsub(".","")
    end

    def format_username
      self.username = self.username.gsub(".","").gsub(/\s+/,"") unless self.username.nil?
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!

  def manage

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit! }
  end




end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: :token

  def token
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def update
    @user = User.find(current_user.id)

    successfully_updated = if needs_password?(@user, params)
                             @user.update_with_password(user_params)
                           else
                             # remove the virtual current_password attribute update_without_password
                             # doesn't know how to ignore it
                             params[:user].delete(:current_password)
                             @user.update_without_password(user_params)
                           end

    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end

  private

  # check if we need password to update user data
  # ie if password or email was changed
  # extend this as needed
  def needs_password?(user, params)
    user.email != params[:user][:email] ||
        params[:user][:password].present? ||
        user.username != params[:user][:username]
  end

  # Using a private method to encapsulate the permissible parameters is
  # just a good pattern since you'll be able to reuse the same permit
  # list between create and update. Also, you can specialize this method
  # with per-user checking of permissible attributes.
  def user_params
    params.require(:user).permit(:avatar, :email, :current_password, :password, :password_confirmation, :username)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.where(:username => params[:username]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end

  def show_title?
    @show_title
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/index.html.haml
- title 'Admin'
%p Welcome to Admin Section.

app/views/admins/manage.html.haml
Here you can manage users

app/views/dashboard/index.html.haml
%h2 Hello, #{current_user.username.humanize}!

app/views/home/secret.html.haml
Pagina secreta

app/views/home/token.html.haml
%h1
  Hello, #{current_user.email}
%p This link (with the auth_token param) will work even if you're not signed in.
%p Save this link, sign out, and try it!

app/views/layouts/application.html.haml
!!! Strict
%html
  %head
    %title= h(yield(:title) || RailStrap::Application.config.application_name )
    = csrf_meta_tag
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag :application
    = yield(:head)
    :css
      /* Sticky footer styles
      -------------------------------------------------- */

      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }

      /* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by its height */
        margin: 0 auto -60px;
        /* Pad bottom by footer height */
        padding: 0 0 60px;
      }

      /* Set the fixed height of the footer here */
      #footer {
        height: 60px;
        background-color: #f5f5f5;
      }


      /* Custom page CSS
      -------------------------------------------------- */
      /* Not required for template or sticky footer method. */

      #wrap > .container {
        padding: 80px 15px 0;
      }
      .container .credit {
        margin: 20px 0;
      }

      #footer > .container {
        padding-left: 15px;
        padding-right: 15px;
      }

      code {
        font-size: 80%;
      }
  %body
    #wrap
      / Fixed navbar
      .navbar.navbar-default.navbar-fixed-top
        .container
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to RailStrap::Application.config.application_name , root_path, :class => 'navbar-brand'
          .collapse.navbar-collapse
            %ul.nav.navbar-nav.pull-right
              - if user_signed_in?
                %li
                  %a{:href => edit_user_registration_path}
                    = fa_icon "cogs"
                    Edit profile
                %li
                  %a{:href => user_profile_path(current_user.username)}
                    = fa_icon "user"
                    Me
                %li= link_to 'Sign out', destroy_user_session_path, method: :delete
              - if admin_signed_in?
                %li= current_admin.email
                %li= link_to 'Admin section', admins_path
                %li= link_to 'Manage users', manage_path
                %li= link_to 'Sign out', destroy_admin_session_path, method: :delete
          / /.nav-collapse
      / Begin page content
      .container.container-main
        - flash.each do |name, msg|
          %div.alert.alert-info
            = content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String)
        - if show_title?
          %h1= h yield(:title)
        = yield
    #footer
      .container
        %p.text-muted.credit
          = RailStrap::Application.config.application_name
          @ #{Time.now.year}.

app/views/users/show.html.haml
.row
  .col-sm-12.col-md-5.col-md-offset-3
    .thumbnail
      %img{alt: "...", :src => @user.avatar.url}/
      .caption.center
        %h3 #{@user.username.humanize}
        = fa_icon "envelope"
        = @user.email
        %hr